#!/usr/bin/env node

'use strict';
const inquirer = require('inquirer');
const chalk = require('chalk');
const meow = require('meow');
const { URL } = require('url');
const { getProjects, getValue, getHostame, getSitemap } = require('./lib/utils');

const run = require('.');

const cli = meow(
  `
	Usage
    $ visual-tester <cmd>

  Cmd
    test      Compare with reference images
    approve   Approve test
    reference Generate reference images

	Options
    --query       Add query params to page request
    --config-dir  Specify custom directory to search for project configs

	Examples
	  $ visual-tester test --query 'optimize-css=0'
`,
  {
    flags: {
      query: {
        type: 'string',
      },
    },
  }
);

const getProject = async () => {
  const { configDir } = cli.flags;
  const choices1 = await getProjects(process.cwd());
  const choices2 = configDir ? await getProjects(configDir) : [];
  const choices3 = await getProjects();

  const choices = [...choices1, ...choices2, ...choices3];

  if (choices.length === 0) {
    console.log(`${chalk.red('Error, no project specified!')}`);
  }

  if (choices.length === 1) {
    const { value: project } = choices[0];
    return project;
  }

  const { project } = await inquirer.prompt({
    type: 'list',
    name: 'project',
    message: 'Choose project',
    choices,
  });

  return project;
};

const getEnvironmentFromSitemap = async sitemap => {
  const url = new URL(sitemap);
  const environment = {
    host: url.origin,
    user: url.username,
    pass: url.password,
    sitemap: url.pathname,
  };

  return {
    ...environment,
    uid: url.hostname,
    urls: await getSitemap(environment),
  };
};

const getEnvironment = async project => {
  const { value } = project || {};
  const config = typeof value === 'string' ? require(value) : value;
  const { environments = [], urls, ...args } = config;
  const choices = await getValue(environments);
  if (choices.length === 0) {
    return {
      ...args,
      uid: project.name.toLowerCase(),
      urls: await getValue(urls),
    };
  }

  if (choices.length === 1) {
    const { value: environment } = choices[0];
    return {
      ...args,
      ...environment,
      uid: `${project.name.toLowerCase()}/${getHostame(environment)}`,
      urls: urls
        ? await getValue(urls, { ...environment, urls: await getSitemap(environment) })
        : await getSitemap(environment),
    };
  }

  const { environment } = await inquirer.prompt({
    type: 'list',
    name: 'environment',
    message: 'Choose environment',
    choices,
  });

  return {
    ...args,
    ...environment,
    uid: `${project.name.toLowerCase()}/${getHostame(environment)}`,
    urls: urls
      ? await getValue(urls, { ...environment, urls: await getSitemap(environment) })
      : await getSitemap(environment),
  };
};

// Run
(async () => {
  const [cmd = 'test', sitemap = ''] = cli.input;
  const fromSitemap = /\:\/\//.test(sitemap);

  const project = fromSitemap ? {} : await getProject();
  const environment = fromSitemap ? await getEnvironmentFromSitemap(sitemap) : await getEnvironment(project);

  await run({ ...environment, ...cli.flags }, cmd);
})();
