const path = require('path');
const globby = require('globby');

/**
 * Token generated by concatenating username and password with `:` character within a base64 encoded string.
 * @param  {String} user User identifier.
 * @param  {String} pass Password.
 * @returns {String} Base64 encoded authentication token.
 */
module.exports.getAuthToken = (user, pass) => `Basic ${Buffer.from([user, pass].join(':')).toString('base64')}`;

/**
 * Get locations from sitemap
 * @param {String} xml
 */
module.exports.getUrlsFromSitemap = xml => {
  const locs = [];
  (xml || '').replace(/<loc>(.*)<\/loc>/gim, (_, m1) => locs.push(m1));
  return locs;
};

/**
 * Hostname from environment
 * @param {Object} environment
 */
module.exports.getHostame = environment => {
  const { host } = environment;
  const { hostname } = new URL(host);
  return hostname;
};

module.exports.getProjects = async (configDir = '') => {
  const cwd = configDir || path.join(__dirname, '../projects');
  const files = await globby('*.config.js', { cwd });

  const getName = file => file.charAt(0).toUpperCase() + file.slice(1).replace('.config.js', '');
  const getPath = file => path.join(cwd, file);

  return files.map(file => ({
    name: getName(file),
    value: getPath(file),
  }));
};

module.exports.getValue = (cmd, ...args) => {
  if (typeof cmd === 'function') {
    return cmd(...args);
  }

  return cmd;
};
